version: '2'

services:
  generate-certs:
    container_name: generate-certs
    image: staticfloat/nginx-certbot
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx-custom.template:/etc/nginx/conf.d/nginx-custom.template
      - ../data-dir/certificates:/etc/letsencrypt/live
    environment:
      - CERTBOT_EMAIL=${CORPORATE_EMAIL}
      - DOMAIN=${DOMAIN}
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx-custom.template > /etc/nginx/conf.d/default.conf && /scripts/entrypoint.sh"
